# TCL File Generated by Component Editor 16.0
# Thu Jul 28 17:41:46 CEST 2016
# DO NOT MODIFY


# 
# Beamformer "Beamformer" v1.0
#  2016.07.28.17:41:46
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module Beamformer
# 
set_module_property DESCRIPTION ""
set_module_property NAME Beamformer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Beamformer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Beamformer_Adder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Beamformer_Adder.vhd VHDL PATH ../hdl/Beamformer_Adder.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH NATURAL 32 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE NATURAL
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point Source_Beam
# 
add_interface Source_Beam avalon_streaming start
set_interface_property Source_Beam associatedClock clock
set_interface_property Source_Beam associatedReset reset
set_interface_property Source_Beam dataBitsPerSymbol 8
set_interface_property Source_Beam errorDescriptor ""
set_interface_property Source_Beam firstSymbolInHighOrderBits true
set_interface_property Source_Beam maxChannel 0
set_interface_property Source_Beam readyLatency 0
set_interface_property Source_Beam ENABLED true
set_interface_property Source_Beam EXPORT_OF ""
set_interface_property Source_Beam PORT_NAME_MAP ""
set_interface_property Source_Beam CMSIS_SVD_VARIABLES ""
set_interface_property Source_Beam SVD_ADDRESS_GROUP ""

add_interface_port Source_Beam Audio_Ready ready Input 1
add_interface_port Source_Beam Audio_Valid valid Output 1
add_interface_port Source_Beam Audio_data data Output data_width


# 
# connection point Sink_FIR
# 
add_interface Sink_FIR avalon_streaming end
set_interface_property Sink_FIR associatedClock clock
set_interface_property Sink_FIR associatedReset reset
set_interface_property Sink_FIR dataBitsPerSymbol 32
set_interface_property Sink_FIR errorDescriptor ""
set_interface_property Sink_FIR firstSymbolInHighOrderBits true
set_interface_property Sink_FIR maxChannel 0
set_interface_property Sink_FIR readyLatency 0
set_interface_property Sink_FIR ENABLED true
set_interface_property Sink_FIR EXPORT_OF ""
set_interface_property Sink_FIR PORT_NAME_MAP ""
set_interface_property Sink_FIR CMSIS_SVD_VARIABLES ""
set_interface_property Sink_FIR SVD_ADDRESS_GROUP ""

add_interface_port Sink_FIR FIR_data data Input data_width
add_interface_port Sink_FIR FIR_Valid valid Input 1
add_interface_port Sink_FIR FIR_Ready ready Output 1
add_interface_port Sink_FIR FIR_sop startofpacket Input 1
add_interface_port Sink_FIR FIR_eop endofpacket Input 1
add_interface_port Sink_FIR FIR_channel channel Input 6

