#ifndef _ALTERA_HPS_0_BRIDGES_H_
#define _ALTERA_HPS_0_BRIDGES_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'Pyramic_Array' in
 * file '/home/ferry/Pyramic/fpga/Altera Project/Project/MIC_ARRAY/hw/quartus/Pyramic_Array.swinfo'.
 */

/*
 * This file contains macros for module 'hps_0_bridges' and devices
 * connected to the following masters:
 *   axi_f2h
 *   h2f_lw
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'SPI_System_0', class 'SPI_System'
 * The macros are prefixed with 'SPI_SYSTEM_0_'.
 * The prefix is the slave descriptor.
 */
#define SPI_SYSTEM_0_COMPONENT_TYPE SPI_System
#define SPI_SYSTEM_0_COMPONENT_NAME SPI_System_0
#define SPI_SYSTEM_0_BASE 0x0
#define SPI_SYSTEM_0_SPAN 32
#define SPI_SYSTEM_0_END 0x1f

/*
 * Macros for device 'audio_and_video_config_0', class 'altera_up_avalon_audio_and_video_config'
 * The macros are prefixed with 'AUDIO_AND_VIDEO_CONFIG_0_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_AND_VIDEO_CONFIG_0_COMPONENT_TYPE altera_up_avalon_audio_and_video_config
#define AUDIO_AND_VIDEO_CONFIG_0_COMPONENT_NAME audio_and_video_config_0
#define AUDIO_AND_VIDEO_CONFIG_0_BASE 0x20
#define AUDIO_AND_VIDEO_CONFIG_0_SPAN 16
#define AUDIO_AND_VIDEO_CONFIG_0_END 0x2f


#endif /* _ALTERA_HPS_0_BRIDGES_H_ */
