# TCL File Generated by Component Editor 16.0
# Mon Nov 21 10:49:24 CET 2016
# DO NOT MODIFY


# 
# Output_Switcher "Output Switcher" v1.0
#  2016.11.21.10:49:24
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module Output_Switcher
# 
set_module_property DESCRIPTION ""
set_module_property NAME Output_Switcher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Output Switcher"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Output_Buffer_Driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Output_Buffer_Driver.vhd VHDL PATH ../hdl/Output_Buffer_Driver.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SAMPLE_WIDTH NATURAL 32
set_parameter_property SAMPLE_WIDTH DEFAULT_VALUE 32
set_parameter_property SAMPLE_WIDTH DISPLAY_NAME SAMPLE_WIDTH
set_parameter_property SAMPLE_WIDTH TYPE NATURAL
set_parameter_property SAMPLE_WIDTH UNITS None
set_parameter_property SAMPLE_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property SAMPLE_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point source_select
# 
add_interface source_select conduit end
set_interface_property source_select associatedClock clock
set_interface_property source_select associatedReset ""
set_interface_property source_select ENABLED true
set_interface_property source_select EXPORT_OF ""
set_interface_property source_select PORT_NAME_MAP ""
set_interface_property source_select CMSIS_SVD_VARIABLES ""
set_interface_property source_select SVD_ADDRESS_GROUP ""

add_interface_port source_select Use_Memory new_signal Input 1
add_interface_port source_select Is_LeftRight new_signal_1 Input 1


# 
# connection point DMA
# 
add_interface DMA avalon start
set_interface_property DMA addressUnits SYMBOLS
set_interface_property DMA associatedClock clock
set_interface_property DMA associatedReset reset
set_interface_property DMA bitsPerSymbol 8
set_interface_property DMA burstOnBurstBoundariesOnly false
set_interface_property DMA burstcountUnits WORDS
set_interface_property DMA doStreamReads false
set_interface_property DMA doStreamWrites false
set_interface_property DMA holdTime 0
set_interface_property DMA linewrapBursts false
set_interface_property DMA maximumPendingReadTransactions 0
set_interface_property DMA maximumPendingWriteTransactions 0
set_interface_property DMA readLatency 0
set_interface_property DMA readWaitTime 1
set_interface_property DMA setupTime 0
set_interface_property DMA timingUnits Cycles
set_interface_property DMA writeWaitTime 0
set_interface_property DMA ENABLED true
set_interface_property DMA EXPORT_OF ""
set_interface_property DMA PORT_NAME_MAP ""
set_interface_property DMA CMSIS_SVD_VARIABLES ""
set_interface_property DMA SVD_ADDRESS_GROUP ""

add_interface_port DMA DMA_Addr address Output 32
add_interface_port DMA DMA_ByteEnable byteenable Output 4
add_interface_port DMA DMA_Read read Output 1
add_interface_port DMA DMA_Data readdata Input 32
add_interface_port DMA DMA_Valid readdatavalid Input 1
add_interface_port DMA DMA_WaitRequest waitrequest Input 1


# 
# connection point Audio_Streaming_Sink
# 
add_interface Audio_Streaming_Sink avalon_streaming end
set_interface_property Audio_Streaming_Sink associatedClock clock
set_interface_property Audio_Streaming_Sink associatedReset reset
set_interface_property Audio_Streaming_Sink dataBitsPerSymbol 8
set_interface_property Audio_Streaming_Sink errorDescriptor ""
set_interface_property Audio_Streaming_Sink firstSymbolInHighOrderBits true
set_interface_property Audio_Streaming_Sink maxChannel 0
set_interface_property Audio_Streaming_Sink readyLatency 0
set_interface_property Audio_Streaming_Sink ENABLED true
set_interface_property Audio_Streaming_Sink EXPORT_OF ""
set_interface_property Audio_Streaming_Sink PORT_NAME_MAP ""
set_interface_property Audio_Streaming_Sink CMSIS_SVD_VARIABLES ""
set_interface_property Audio_Streaming_Sink SVD_ADDRESS_GROUP ""

add_interface_port Audio_Streaming_Sink In_Avalon_Ready ready Output 1
add_interface_port Audio_Streaming_Sink In_Avalon_Valid valid Input 1
add_interface_port Audio_Streaming_Sink In_Avalon_Data data Input sample_width


# 
# connection point Audio_Streaming_Source
# 
add_interface Audio_Streaming_Source avalon_streaming start
set_interface_property Audio_Streaming_Source associatedClock clock
set_interface_property Audio_Streaming_Source associatedReset reset
set_interface_property Audio_Streaming_Source dataBitsPerSymbol 8
set_interface_property Audio_Streaming_Source errorDescriptor ""
set_interface_property Audio_Streaming_Source firstSymbolInHighOrderBits true
set_interface_property Audio_Streaming_Source maxChannel 0
set_interface_property Audio_Streaming_Source readyLatency 0
set_interface_property Audio_Streaming_Source ENABLED true
set_interface_property Audio_Streaming_Source EXPORT_OF ""
set_interface_property Audio_Streaming_Source PORT_NAME_MAP ""
set_interface_property Audio_Streaming_Source CMSIS_SVD_VARIABLES ""
set_interface_property Audio_Streaming_Source SVD_ADDRESS_GROUP ""

add_interface_port Audio_Streaming_Source Out_Avalon_Ready ready Input 1
add_interface_port Audio_Streaming_Source Out_Avalon_Data data Output 32
add_interface_port Audio_Streaming_Source Out_Avalon_Valid valid Output 1

