#ifndef _ALTERA_OUTPUT_SWITCHER_0_H_
#define _ALTERA_OUTPUT_SWITCHER_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'Pyramic_Array' in
 * file '/home/ferry/Pyramic/fpga/Altera Project/Project/MIC_ARRAY/hw/quartus/Pyramic_Array.swinfo'.
 */

/*
 * This file contains macros for module 'Output_Switcher_0' and devices
 * connected to the following master:
 *   DMA
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'hps_0_bridges', class 'hps_bridge_avalon'
 * The macros are prefixed with 'HPS_0_BRIDGES_'.
 * The prefix is the slave descriptor.
 */
#define HPS_0_BRIDGES_COMPONENT_TYPE hps_bridge_avalon
#define HPS_0_BRIDGES_COMPONENT_NAME hps_0_bridges
#define HPS_0_BRIDGES_BASE 0x0
#define HPS_0_BRIDGES_SPAN 0x0
#define HPS_0_BRIDGES_END 0xffffffff


#endif /* _ALTERA_OUTPUT_SWITCHER_0_H_ */
