set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD0]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD1]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD2]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD3]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD0] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_MDIO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDIO]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDC]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CTL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CTL]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD1] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD2] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD3] -to *
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO35] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO35]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO53] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO53]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO54] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO54]