// Pyramic_Array_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module Pyramic_Array_mm_interconnect_0 (
		input  wire        pll_0_outclk0_clk,                                                  //                                                pll_0_outclk0.clk
		input  wire        hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset, // hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset.reset
		input  wire        Output_Switcher_0_reset_reset_bridge_in_reset_reset,                //                Output_Switcher_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] Output_Switcher_0_DMA_address,                                      //                                        Output_Switcher_0_DMA.address
		output wire        Output_Switcher_0_DMA_waitrequest,                                  //                                                             .waitrequest
		input  wire [3:0]  Output_Switcher_0_DMA_byteenable,                                   //                                                             .byteenable
		input  wire        Output_Switcher_0_DMA_read,                                         //                                                             .read
		output wire [31:0] Output_Switcher_0_DMA_readdata,                                     //                                                             .readdata
		output wire        Output_Switcher_0_DMA_readdatavalid,                                //                                                             .readdatavalid
		input  wire [31:0] SPI_System_0_avalon_master_address,                                 //                                   SPI_System_0_avalon_master.address
		output wire        SPI_System_0_avalon_master_waitrequest,                             //                                                             .waitrequest
		input  wire [2:0]  SPI_System_0_avalon_master_burstcount,                              //                                                             .burstcount
		input  wire [3:0]  SPI_System_0_avalon_master_byteenable,                              //                                                             .byteenable
		input  wire        SPI_System_0_avalon_master_write,                                   //                                                             .write
		input  wire [31:0] SPI_System_0_avalon_master_writedata,                               //                                                             .writedata
		output wire [29:0] hps_0_f2h_sdram0_data_address,                                      //                                        hps_0_f2h_sdram0_data.address
		output wire        hps_0_f2h_sdram0_data_write,                                        //                                                             .write
		output wire        hps_0_f2h_sdram0_data_read,                                         //                                                             .read
		input  wire [31:0] hps_0_f2h_sdram0_data_readdata,                                     //                                                             .readdata
		output wire [31:0] hps_0_f2h_sdram0_data_writedata,                                    //                                                             .writedata
		output wire [7:0]  hps_0_f2h_sdram0_data_burstcount,                                   //                                                             .burstcount
		output wire [3:0]  hps_0_f2h_sdram0_data_byteenable,                                   //                                                             .byteenable
		input  wire        hps_0_f2h_sdram0_data_readdatavalid,                                //                                                             .readdatavalid
		input  wire        hps_0_f2h_sdram0_data_waitrequest                                   //                                                             .waitrequest
	);

	wire          output_switcher_0_dma_translator_avalon_universal_master_0_waitrequest;        // Output_Switcher_0_DMA_agent:av_waitrequest -> Output_Switcher_0_DMA_translator:uav_waitrequest
	wire   [31:0] output_switcher_0_dma_translator_avalon_universal_master_0_readdata;           // Output_Switcher_0_DMA_agent:av_readdata -> Output_Switcher_0_DMA_translator:uav_readdata
	wire          output_switcher_0_dma_translator_avalon_universal_master_0_debugaccess;        // Output_Switcher_0_DMA_translator:uav_debugaccess -> Output_Switcher_0_DMA_agent:av_debugaccess
	wire   [31:0] output_switcher_0_dma_translator_avalon_universal_master_0_address;            // Output_Switcher_0_DMA_translator:uav_address -> Output_Switcher_0_DMA_agent:av_address
	wire          output_switcher_0_dma_translator_avalon_universal_master_0_read;               // Output_Switcher_0_DMA_translator:uav_read -> Output_Switcher_0_DMA_agent:av_read
	wire    [3:0] output_switcher_0_dma_translator_avalon_universal_master_0_byteenable;         // Output_Switcher_0_DMA_translator:uav_byteenable -> Output_Switcher_0_DMA_agent:av_byteenable
	wire          output_switcher_0_dma_translator_avalon_universal_master_0_readdatavalid;      // Output_Switcher_0_DMA_agent:av_readdatavalid -> Output_Switcher_0_DMA_translator:uav_readdatavalid
	wire          output_switcher_0_dma_translator_avalon_universal_master_0_lock;               // Output_Switcher_0_DMA_translator:uav_lock -> Output_Switcher_0_DMA_agent:av_lock
	wire          output_switcher_0_dma_translator_avalon_universal_master_0_write;              // Output_Switcher_0_DMA_translator:uav_write -> Output_Switcher_0_DMA_agent:av_write
	wire   [31:0] output_switcher_0_dma_translator_avalon_universal_master_0_writedata;          // Output_Switcher_0_DMA_translator:uav_writedata -> Output_Switcher_0_DMA_agent:av_writedata
	wire    [2:0] output_switcher_0_dma_translator_avalon_universal_master_0_burstcount;         // Output_Switcher_0_DMA_translator:uav_burstcount -> Output_Switcher_0_DMA_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                             // rsp_mux:src_valid -> Output_Switcher_0_DMA_agent:rp_valid
	wire  [108:0] rsp_mux_src_data;                                                              // rsp_mux:src_data -> Output_Switcher_0_DMA_agent:rp_data
	wire          rsp_mux_src_ready;                                                             // Output_Switcher_0_DMA_agent:rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                           // rsp_mux:src_channel -> Output_Switcher_0_DMA_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                     // rsp_mux:src_startofpacket -> Output_Switcher_0_DMA_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                       // rsp_mux:src_endofpacket -> Output_Switcher_0_DMA_agent:rp_endofpacket
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // SPI_System_0_avalon_master_agent:av_waitrequest -> SPI_System_0_avalon_master_translator:uav_waitrequest
	wire   [31:0] spi_system_0_avalon_master_translator_avalon_universal_master_0_readdata;      // SPI_System_0_avalon_master_agent:av_readdata -> SPI_System_0_avalon_master_translator:uav_readdata
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // SPI_System_0_avalon_master_translator:uav_debugaccess -> SPI_System_0_avalon_master_agent:av_debugaccess
	wire   [31:0] spi_system_0_avalon_master_translator_avalon_universal_master_0_address;       // SPI_System_0_avalon_master_translator:uav_address -> SPI_System_0_avalon_master_agent:av_address
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_read;          // SPI_System_0_avalon_master_translator:uav_read -> SPI_System_0_avalon_master_agent:av_read
	wire    [3:0] spi_system_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // SPI_System_0_avalon_master_translator:uav_byteenable -> SPI_System_0_avalon_master_agent:av_byteenable
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // SPI_System_0_avalon_master_agent:av_readdatavalid -> SPI_System_0_avalon_master_translator:uav_readdatavalid
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_lock;          // SPI_System_0_avalon_master_translator:uav_lock -> SPI_System_0_avalon_master_agent:av_lock
	wire          spi_system_0_avalon_master_translator_avalon_universal_master_0_write;         // SPI_System_0_avalon_master_translator:uav_write -> SPI_System_0_avalon_master_agent:av_write
	wire   [31:0] spi_system_0_avalon_master_translator_avalon_universal_master_0_writedata;     // SPI_System_0_avalon_master_translator:uav_writedata -> SPI_System_0_avalon_master_agent:av_writedata
	wire    [4:0] spi_system_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // SPI_System_0_avalon_master_translator:uav_burstcount -> SPI_System_0_avalon_master_agent:av_burstcount
	wire          rsp_mux_001_src_valid;                                                         // rsp_mux_001:src_valid -> SPI_System_0_avalon_master_agent:rp_valid
	wire  [108:0] rsp_mux_001_src_data;                                                          // rsp_mux_001:src_data -> SPI_System_0_avalon_master_agent:rp_data
	wire          rsp_mux_001_src_ready;                                                         // SPI_System_0_avalon_master_agent:rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                                       // rsp_mux_001:src_channel -> SPI_System_0_avalon_master_agent:rp_channel
	wire          rsp_mux_001_src_startofpacket;                                                 // rsp_mux_001:src_startofpacket -> SPI_System_0_avalon_master_agent:rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                                                   // rsp_mux_001:src_endofpacket -> SPI_System_0_avalon_master_agent:rp_endofpacket
	wire   [31:0] hps_0_f2h_sdram0_data_agent_m0_readdata;                                       // hps_0_f2h_sdram0_data_translator:uav_readdata -> hps_0_f2h_sdram0_data_agent:m0_readdata
	wire          hps_0_f2h_sdram0_data_agent_m0_waitrequest;                                    // hps_0_f2h_sdram0_data_translator:uav_waitrequest -> hps_0_f2h_sdram0_data_agent:m0_waitrequest
	wire          hps_0_f2h_sdram0_data_agent_m0_debugaccess;                                    // hps_0_f2h_sdram0_data_agent:m0_debugaccess -> hps_0_f2h_sdram0_data_translator:uav_debugaccess
	wire   [31:0] hps_0_f2h_sdram0_data_agent_m0_address;                                        // hps_0_f2h_sdram0_data_agent:m0_address -> hps_0_f2h_sdram0_data_translator:uav_address
	wire    [3:0] hps_0_f2h_sdram0_data_agent_m0_byteenable;                                     // hps_0_f2h_sdram0_data_agent:m0_byteenable -> hps_0_f2h_sdram0_data_translator:uav_byteenable
	wire          hps_0_f2h_sdram0_data_agent_m0_read;                                           // hps_0_f2h_sdram0_data_agent:m0_read -> hps_0_f2h_sdram0_data_translator:uav_read
	wire          hps_0_f2h_sdram0_data_agent_m0_readdatavalid;                                  // hps_0_f2h_sdram0_data_translator:uav_readdatavalid -> hps_0_f2h_sdram0_data_agent:m0_readdatavalid
	wire          hps_0_f2h_sdram0_data_agent_m0_lock;                                           // hps_0_f2h_sdram0_data_agent:m0_lock -> hps_0_f2h_sdram0_data_translator:uav_lock
	wire   [31:0] hps_0_f2h_sdram0_data_agent_m0_writedata;                                      // hps_0_f2h_sdram0_data_agent:m0_writedata -> hps_0_f2h_sdram0_data_translator:uav_writedata
	wire          hps_0_f2h_sdram0_data_agent_m0_write;                                          // hps_0_f2h_sdram0_data_agent:m0_write -> hps_0_f2h_sdram0_data_translator:uav_write
	wire    [9:0] hps_0_f2h_sdram0_data_agent_m0_burstcount;                                     // hps_0_f2h_sdram0_data_agent:m0_burstcount -> hps_0_f2h_sdram0_data_translator:uav_burstcount
	wire          hps_0_f2h_sdram0_data_agent_rf_source_valid;                                   // hps_0_f2h_sdram0_data_agent:rf_source_valid -> hps_0_f2h_sdram0_data_agent_rsp_fifo:in_valid
	wire  [109:0] hps_0_f2h_sdram0_data_agent_rf_source_data;                                    // hps_0_f2h_sdram0_data_agent:rf_source_data -> hps_0_f2h_sdram0_data_agent_rsp_fifo:in_data
	wire          hps_0_f2h_sdram0_data_agent_rf_source_ready;                                   // hps_0_f2h_sdram0_data_agent_rsp_fifo:in_ready -> hps_0_f2h_sdram0_data_agent:rf_source_ready
	wire          hps_0_f2h_sdram0_data_agent_rf_source_startofpacket;                           // hps_0_f2h_sdram0_data_agent:rf_source_startofpacket -> hps_0_f2h_sdram0_data_agent_rsp_fifo:in_startofpacket
	wire          hps_0_f2h_sdram0_data_agent_rf_source_endofpacket;                             // hps_0_f2h_sdram0_data_agent:rf_source_endofpacket -> hps_0_f2h_sdram0_data_agent_rsp_fifo:in_endofpacket
	wire          hps_0_f2h_sdram0_data_agent_rsp_fifo_out_valid;                                // hps_0_f2h_sdram0_data_agent_rsp_fifo:out_valid -> hps_0_f2h_sdram0_data_agent:rf_sink_valid
	wire  [109:0] hps_0_f2h_sdram0_data_agent_rsp_fifo_out_data;                                 // hps_0_f2h_sdram0_data_agent_rsp_fifo:out_data -> hps_0_f2h_sdram0_data_agent:rf_sink_data
	wire          hps_0_f2h_sdram0_data_agent_rsp_fifo_out_ready;                                // hps_0_f2h_sdram0_data_agent:rf_sink_ready -> hps_0_f2h_sdram0_data_agent_rsp_fifo:out_ready
	wire          hps_0_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket;                        // hps_0_f2h_sdram0_data_agent_rsp_fifo:out_startofpacket -> hps_0_f2h_sdram0_data_agent:rf_sink_startofpacket
	wire          hps_0_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket;                          // hps_0_f2h_sdram0_data_agent_rsp_fifo:out_endofpacket -> hps_0_f2h_sdram0_data_agent:rf_sink_endofpacket
	wire          cmd_mux_src_valid;                                                             // cmd_mux:src_valid -> hps_0_f2h_sdram0_data_agent:cp_valid
	wire  [108:0] cmd_mux_src_data;                                                              // cmd_mux:src_data -> hps_0_f2h_sdram0_data_agent:cp_data
	wire          cmd_mux_src_ready;                                                             // hps_0_f2h_sdram0_data_agent:cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                           // cmd_mux:src_channel -> hps_0_f2h_sdram0_data_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                                     // cmd_mux:src_startofpacket -> hps_0_f2h_sdram0_data_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                       // cmd_mux:src_endofpacket -> hps_0_f2h_sdram0_data_agent:cp_endofpacket
	wire          output_switcher_0_dma_agent_cp_valid;                                          // Output_Switcher_0_DMA_agent:cp_valid -> router:sink_valid
	wire  [108:0] output_switcher_0_dma_agent_cp_data;                                           // Output_Switcher_0_DMA_agent:cp_data -> router:sink_data
	wire          output_switcher_0_dma_agent_cp_ready;                                          // router:sink_ready -> Output_Switcher_0_DMA_agent:cp_ready
	wire          output_switcher_0_dma_agent_cp_startofpacket;                                  // Output_Switcher_0_DMA_agent:cp_startofpacket -> router:sink_startofpacket
	wire          output_switcher_0_dma_agent_cp_endofpacket;                                    // Output_Switcher_0_DMA_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                              // router:src_valid -> cmd_demux:sink_valid
	wire  [108:0] router_src_data;                                                               // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                              // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                            // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                      // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                        // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          spi_system_0_avalon_master_agent_cp_valid;                                     // SPI_System_0_avalon_master_agent:cp_valid -> router_001:sink_valid
	wire  [108:0] spi_system_0_avalon_master_agent_cp_data;                                      // SPI_System_0_avalon_master_agent:cp_data -> router_001:sink_data
	wire          spi_system_0_avalon_master_agent_cp_ready;                                     // router_001:sink_ready -> SPI_System_0_avalon_master_agent:cp_ready
	wire          spi_system_0_avalon_master_agent_cp_startofpacket;                             // SPI_System_0_avalon_master_agent:cp_startofpacket -> router_001:sink_startofpacket
	wire          spi_system_0_avalon_master_agent_cp_endofpacket;                               // SPI_System_0_avalon_master_agent:cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                          // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [108:0] router_001_src_data;                                                           // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                                          // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                                        // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                                                  // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                                                    // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          hps_0_f2h_sdram0_data_agent_rp_valid;                                          // hps_0_f2h_sdram0_data_agent:rp_valid -> router_002:sink_valid
	wire  [108:0] hps_0_f2h_sdram0_data_agent_rp_data;                                           // hps_0_f2h_sdram0_data_agent:rp_data -> router_002:sink_data
	wire          hps_0_f2h_sdram0_data_agent_rp_ready;                                          // router_002:sink_ready -> hps_0_f2h_sdram0_data_agent:rp_ready
	wire          hps_0_f2h_sdram0_data_agent_rp_startofpacket;                                  // hps_0_f2h_sdram0_data_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          hps_0_f2h_sdram0_data_agent_rp_endofpacket;                                    // hps_0_f2h_sdram0_data_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                                          // router_002:src_valid -> rsp_demux:sink_valid
	wire  [108:0] router_002_src_data;                                                           // router_002:src_data -> rsp_demux:sink_data
	wire          router_002_src_ready;                                                          // rsp_demux:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                                        // router_002:src_channel -> rsp_demux:sink_channel
	wire          router_002_src_startofpacket;                                                  // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_002_src_endofpacket;                                                    // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                          // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [108:0] cmd_demux_src0_data;                                                           // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                          // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                                        // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                  // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                    // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                                      // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [108:0] cmd_demux_001_src0_data;                                                       // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire          cmd_demux_001_src0_ready;                                                      // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                                                    // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire          cmd_demux_001_src0_startofpacket;                                              // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                                                // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                                                          // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [108:0] rsp_demux_src0_data;                                                           // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                          // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                                        // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                  // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                    // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                                                          // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [108:0] rsp_demux_src1_data;                                                           // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire          rsp_demux_src1_ready;                                                          // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                                                        // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire          rsp_demux_src1_startofpacket;                                                  // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          rsp_demux_src1_endofpacket;                                                    // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire          hps_0_f2h_sdram0_data_agent_rdata_fifo_src_valid;                              // hps_0_f2h_sdram0_data_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] hps_0_f2h_sdram0_data_agent_rdata_fifo_src_data;                               // hps_0_f2h_sdram0_data_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          hps_0_f2h_sdram0_data_agent_rdata_fifo_src_ready;                              // avalon_st_adapter:in_0_ready -> hps_0_f2h_sdram0_data_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                                 // avalon_st_adapter:out_0_valid -> hps_0_f2h_sdram0_data_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                                  // avalon_st_adapter:out_0_data -> hps_0_f2h_sdram0_data_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                                 // hps_0_f2h_sdram0_data_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                                 // avalon_st_adapter:out_0_error -> hps_0_f2h_sdram0_data_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) output_switcher_0_dma_translator (
		.clk                    (pll_0_outclk0_clk),                                                        //                       clk.clk
		.reset                  (Output_Switcher_0_reset_reset_bridge_in_reset_reset),                      //                     reset.reset
		.uav_address            (output_switcher_0_dma_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (output_switcher_0_dma_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (output_switcher_0_dma_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (output_switcher_0_dma_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (output_switcher_0_dma_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (output_switcher_0_dma_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (output_switcher_0_dma_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (output_switcher_0_dma_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (output_switcher_0_dma_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (output_switcher_0_dma_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (output_switcher_0_dma_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (Output_Switcher_0_DMA_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (Output_Switcher_0_DMA_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (Output_Switcher_0_DMA_byteenable),                                         //                          .byteenable
		.av_read                (Output_Switcher_0_DMA_read),                                               //                          .read
		.av_readdata            (Output_Switcher_0_DMA_readdata),                                           //                          .readdata
		.av_readdatavalid       (Output_Switcher_0_DMA_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                     //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                     //               (terminated)
		.av_begintransfer       (1'b0),                                                                     //               (terminated)
		.av_chipselect          (1'b0),                                                                     //               (terminated)
		.av_write               (1'b0),                                                                     //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                     //               (terminated)
		.av_lock                (1'b0),                                                                     //               (terminated)
		.av_debugaccess         (1'b0),                                                                     //               (terminated)
		.uav_clken              (),                                                                         //               (terminated)
		.av_clken               (1'b1),                                                                     //               (terminated)
		.uav_response           (2'b00),                                                                    //               (terminated)
		.av_response            (),                                                                         //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                     //               (terminated)
		.av_writeresponsevalid  ()                                                                          //               (terminated)
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (3),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (5),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) spi_system_0_avalon_master_translator (
		.clk                    (pll_0_outclk0_clk),                                                             //                       clk.clk
		.reset                  (Output_Switcher_0_reset_reset_bridge_in_reset_reset),                           //                     reset.reset
		.uav_address            (spi_system_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (spi_system_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (spi_system_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (spi_system_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (spi_system_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (spi_system_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (spi_system_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (spi_system_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (spi_system_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (spi_system_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (spi_system_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (SPI_System_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (SPI_System_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (SPI_System_0_avalon_master_burstcount),                                         //                          .burstcount
		.av_byteenable          (SPI_System_0_avalon_master_byteenable),                                         //                          .byteenable
		.av_write               (SPI_System_0_avalon_master_write),                                              //                          .write
		.av_writedata           (SPI_System_0_avalon_master_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                          //               (terminated)
		.av_read                (1'b0),                                                                          //               (terminated)
		.av_readdata            (),                                                                              //               (terminated)
		.av_readdatavalid       (),                                                                              //               (terminated)
		.av_lock                (1'b0),                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                         //               (terminated)
		.av_response            (),                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (30),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (10),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) hps_0_f2h_sdram0_data_translator (
		.clk                    (pll_0_outclk0_clk),                                                  //                      clk.clk
		.reset                  (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (hps_0_f2h_sdram0_data_agent_m0_address),                             // avalon_universal_slave_0.address
		.uav_burstcount         (hps_0_f2h_sdram0_data_agent_m0_burstcount),                          //                         .burstcount
		.uav_read               (hps_0_f2h_sdram0_data_agent_m0_read),                                //                         .read
		.uav_write              (hps_0_f2h_sdram0_data_agent_m0_write),                               //                         .write
		.uav_waitrequest        (hps_0_f2h_sdram0_data_agent_m0_waitrequest),                         //                         .waitrequest
		.uav_readdatavalid      (hps_0_f2h_sdram0_data_agent_m0_readdatavalid),                       //                         .readdatavalid
		.uav_byteenable         (hps_0_f2h_sdram0_data_agent_m0_byteenable),                          //                         .byteenable
		.uav_readdata           (hps_0_f2h_sdram0_data_agent_m0_readdata),                            //                         .readdata
		.uav_writedata          (hps_0_f2h_sdram0_data_agent_m0_writedata),                           //                         .writedata
		.uav_lock               (hps_0_f2h_sdram0_data_agent_m0_lock),                                //                         .lock
		.uav_debugaccess        (hps_0_f2h_sdram0_data_agent_m0_debugaccess),                         //                         .debugaccess
		.av_address             (hps_0_f2h_sdram0_data_address),                                      //      avalon_anti_slave_0.address
		.av_write               (hps_0_f2h_sdram0_data_write),                                        //                         .write
		.av_read                (hps_0_f2h_sdram0_data_read),                                         //                         .read
		.av_readdata            (hps_0_f2h_sdram0_data_readdata),                                     //                         .readdata
		.av_writedata           (hps_0_f2h_sdram0_data_writedata),                                    //                         .writedata
		.av_burstcount          (hps_0_f2h_sdram0_data_burstcount),                                   //                         .burstcount
		.av_byteenable          (hps_0_f2h_sdram0_data_byteenable),                                   //                         .byteenable
		.av_readdatavalid       (hps_0_f2h_sdram0_data_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (hps_0_f2h_sdram0_data_waitrequest),                                  //                         .waitrequest
		.av_begintransfer       (),                                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                                   //              (terminated)
		.av_writebyteenable     (),                                                                   //              (terminated)
		.av_lock                (),                                                                   //              (terminated)
		.av_chipselect          (),                                                                   //              (terminated)
		.av_clken               (),                                                                   //              (terminated)
		.uav_clken              (1'b0),                                                               //              (terminated)
		.av_debugaccess         (),                                                                   //              (terminated)
		.av_outputenable        (),                                                                   //              (terminated)
		.uav_response           (),                                                                   //              (terminated)
		.av_response            (2'b00),                                                              //              (terminated)
		.uav_writeresponsevalid (),                                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (108),
		.PKT_ORI_BURST_SIZE_L      (106),
		.PKT_RESPONSE_STATUS_H     (105),
		.PKT_RESPONSE_STATUS_L     (104),
		.PKT_QOS_H                 (93),
		.PKT_QOS_L                 (93),
		.PKT_DATA_SIDEBAND_H       (91),
		.PKT_DATA_SIDEBAND_L       (91),
		.PKT_ADDR_SIDEBAND_H       (90),
		.PKT_ADDR_SIDEBAND_L       (90),
		.PKT_BURST_TYPE_H          (89),
		.PKT_BURST_TYPE_L          (88),
		.PKT_CACHE_H               (103),
		.PKT_CACHE_L               (100),
		.PKT_THREAD_ID_H           (96),
		.PKT_THREAD_ID_L           (96),
		.PKT_BURST_SIZE_H          (87),
		.PKT_BURST_SIZE_L          (85),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (92),
		.PKT_PROTECTION_H          (99),
		.PKT_PROTECTION_L          (97),
		.PKT_BURSTWRAP_H           (84),
		.PKT_BURSTWRAP_L           (84),
		.PKT_BYTE_CNT_H            (83),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (94),
		.PKT_SRC_ID_L              (94),
		.PKT_DEST_ID_H             (95),
		.PKT_DEST_ID_L             (95),
		.ST_DATA_W                 (109),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) output_switcher_0_dma_agent (
		.clk                   (pll_0_outclk0_clk),                                                        //       clk.clk
		.reset                 (Output_Switcher_0_reset_reset_bridge_in_reset_reset),                      // clk_reset.reset
		.av_address            (output_switcher_0_dma_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (output_switcher_0_dma_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (output_switcher_0_dma_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (output_switcher_0_dma_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (output_switcher_0_dma_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (output_switcher_0_dma_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (output_switcher_0_dma_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (output_switcher_0_dma_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (output_switcher_0_dma_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (output_switcher_0_dma_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (output_switcher_0_dma_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (output_switcher_0_dma_agent_cp_valid),                                     //        cp.valid
		.cp_data               (output_switcher_0_dma_agent_cp_data),                                      //          .data
		.cp_startofpacket      (output_switcher_0_dma_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (output_switcher_0_dma_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (output_switcher_0_dma_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                        //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                         //          .data
		.rp_channel            (rsp_mux_src_channel),                                                      //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                  //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                        //          .ready
		.av_response           (),                                                                         // (terminated)
		.av_writeresponsevalid ()                                                                          // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (108),
		.PKT_ORI_BURST_SIZE_L      (106),
		.PKT_RESPONSE_STATUS_H     (105),
		.PKT_RESPONSE_STATUS_L     (104),
		.PKT_QOS_H                 (93),
		.PKT_QOS_L                 (93),
		.PKT_DATA_SIDEBAND_H       (91),
		.PKT_DATA_SIDEBAND_L       (91),
		.PKT_ADDR_SIDEBAND_H       (90),
		.PKT_ADDR_SIDEBAND_L       (90),
		.PKT_BURST_TYPE_H          (89),
		.PKT_BURST_TYPE_L          (88),
		.PKT_CACHE_H               (103),
		.PKT_CACHE_L               (100),
		.PKT_THREAD_ID_H           (96),
		.PKT_THREAD_ID_L           (96),
		.PKT_BURST_SIZE_H          (87),
		.PKT_BURST_SIZE_L          (85),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (92),
		.PKT_PROTECTION_H          (99),
		.PKT_PROTECTION_L          (97),
		.PKT_BURSTWRAP_H           (84),
		.PKT_BURSTWRAP_L           (84),
		.PKT_BYTE_CNT_H            (83),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (94),
		.PKT_SRC_ID_L              (94),
		.PKT_DEST_ID_H             (95),
		.PKT_DEST_ID_L             (95),
		.ST_DATA_W                 (109),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (5),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) spi_system_0_avalon_master_agent (
		.clk                   (pll_0_outclk0_clk),                                                             //       clk.clk
		.reset                 (Output_Switcher_0_reset_reset_bridge_in_reset_reset),                           // clk_reset.reset
		.av_address            (spi_system_0_avalon_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (spi_system_0_avalon_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (spi_system_0_avalon_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (spi_system_0_avalon_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (spi_system_0_avalon_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (spi_system_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (spi_system_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (spi_system_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (spi_system_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (spi_system_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (spi_system_0_avalon_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (spi_system_0_avalon_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (spi_system_0_avalon_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (spi_system_0_avalon_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (spi_system_0_avalon_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (spi_system_0_avalon_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_001_src_valid),                                                         //        rp.valid
		.rp_data               (rsp_mux_001_src_data),                                                          //          .data
		.rp_channel            (rsp_mux_001_src_channel),                                                       //          .channel
		.rp_startofpacket      (rsp_mux_001_src_startofpacket),                                                 //          .startofpacket
		.rp_endofpacket        (rsp_mux_001_src_endofpacket),                                                   //          .endofpacket
		.rp_ready              (rsp_mux_001_src_ready),                                                         //          .ready
		.av_response           (),                                                                              // (terminated)
		.av_writeresponsevalid ()                                                                               // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (108),
		.PKT_ORI_BURST_SIZE_L      (106),
		.PKT_RESPONSE_STATUS_H     (105),
		.PKT_RESPONSE_STATUS_L     (104),
		.PKT_BURST_SIZE_H          (87),
		.PKT_BURST_SIZE_L          (85),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (92),
		.PKT_PROTECTION_H          (99),
		.PKT_PROTECTION_L          (97),
		.PKT_BURSTWRAP_H           (84),
		.PKT_BURSTWRAP_L           (84),
		.PKT_BYTE_CNT_H            (83),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (94),
		.PKT_SRC_ID_L              (94),
		.PKT_DEST_ID_H             (95),
		.PKT_DEST_ID_L             (95),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (109),
		.AVS_BURSTCOUNT_W          (10),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) hps_0_f2h_sdram0_data_agent (
		.clk                     (pll_0_outclk0_clk),                                                  //             clk.clk
		.reset                   (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (hps_0_f2h_sdram0_data_agent_m0_address),                             //              m0.address
		.m0_burstcount           (hps_0_f2h_sdram0_data_agent_m0_burstcount),                          //                .burstcount
		.m0_byteenable           (hps_0_f2h_sdram0_data_agent_m0_byteenable),                          //                .byteenable
		.m0_debugaccess          (hps_0_f2h_sdram0_data_agent_m0_debugaccess),                         //                .debugaccess
		.m0_lock                 (hps_0_f2h_sdram0_data_agent_m0_lock),                                //                .lock
		.m0_readdata             (hps_0_f2h_sdram0_data_agent_m0_readdata),                            //                .readdata
		.m0_readdatavalid        (hps_0_f2h_sdram0_data_agent_m0_readdatavalid),                       //                .readdatavalid
		.m0_read                 (hps_0_f2h_sdram0_data_agent_m0_read),                                //                .read
		.m0_waitrequest          (hps_0_f2h_sdram0_data_agent_m0_waitrequest),                         //                .waitrequest
		.m0_writedata            (hps_0_f2h_sdram0_data_agent_m0_writedata),                           //                .writedata
		.m0_write                (hps_0_f2h_sdram0_data_agent_m0_write),                               //                .write
		.rp_endofpacket          (hps_0_f2h_sdram0_data_agent_rp_endofpacket),                         //              rp.endofpacket
		.rp_ready                (hps_0_f2h_sdram0_data_agent_rp_ready),                               //                .ready
		.rp_valid                (hps_0_f2h_sdram0_data_agent_rp_valid),                               //                .valid
		.rp_data                 (hps_0_f2h_sdram0_data_agent_rp_data),                                //                .data
		.rp_startofpacket        (hps_0_f2h_sdram0_data_agent_rp_startofpacket),                       //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                                  //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                                  //                .valid
		.cp_data                 (cmd_mux_src_data),                                                   //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                                          //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                            //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                                //                .channel
		.rf_sink_ready           (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //         rf_sink.ready
		.rf_sink_valid           (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //                .valid
		.rf_sink_startofpacket   (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //                .startofpacket
		.rf_sink_endofpacket     (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //                .endofpacket
		.rf_sink_data            (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //                .data
		.rf_source_ready         (hps_0_f2h_sdram0_data_agent_rf_source_ready),                        //       rf_source.ready
		.rf_source_valid         (hps_0_f2h_sdram0_data_agent_rf_source_valid),                        //                .valid
		.rf_source_startofpacket (hps_0_f2h_sdram0_data_agent_rf_source_startofpacket),                //                .startofpacket
		.rf_source_endofpacket   (hps_0_f2h_sdram0_data_agent_rf_source_endofpacket),                  //                .endofpacket
		.rf_source_data          (hps_0_f2h_sdram0_data_agent_rf_source_data),                         //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                      // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                      //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                       //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                      //                .error
		.rdata_fifo_src_ready    (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //                .valid
		.rdata_fifo_src_data     (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //                .data
		.m0_response             (2'b00),                                                              //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (110),
		.FIFO_DEPTH          (15),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) hps_0_f2h_sdram0_data_agent_rsp_fifo (
		.clk               (pll_0_outclk0_clk),                                                  //       clk.clk
		.reset             (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (hps_0_f2h_sdram0_data_agent_rf_source_data),                         //        in.data
		.in_valid          (hps_0_f2h_sdram0_data_agent_rf_source_valid),                        //          .valid
		.in_ready          (hps_0_f2h_sdram0_data_agent_rf_source_ready),                        //          .ready
		.in_startofpacket  (hps_0_f2h_sdram0_data_agent_rf_source_startofpacket),                //          .startofpacket
		.in_endofpacket    (hps_0_f2h_sdram0_data_agent_rf_source_endofpacket),                  //          .endofpacket
		.out_data          (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //       out.data
		.out_valid         (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //          .valid
		.out_ready         (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //          .ready
		.out_startofpacket (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //          .startofpacket
		.out_endofpacket   (hps_0_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //          .endofpacket
		.csr_address       (2'b00),                                                              // (terminated)
		.csr_read          (1'b0),                                                               // (terminated)
		.csr_write         (1'b0),                                                               // (terminated)
		.csr_readdata      (),                                                                   // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                               // (terminated)
		.almost_full_data  (),                                                                   // (terminated)
		.almost_empty_data (),                                                                   // (terminated)
		.in_empty          (1'b0),                                                               // (terminated)
		.out_empty         (),                                                                   // (terminated)
		.in_error          (1'b0),                                                               // (terminated)
		.out_error         (),                                                                   // (terminated)
		.in_channel        (1'b0),                                                               // (terminated)
		.out_channel       ()                                                                    // (terminated)
	);

	Pyramic_Array_mm_interconnect_0_router router (
		.sink_ready         (output_switcher_0_dma_agent_cp_ready),                //      sink.ready
		.sink_valid         (output_switcher_0_dma_agent_cp_valid),                //          .valid
		.sink_data          (output_switcher_0_dma_agent_cp_data),                 //          .data
		.sink_startofpacket (output_switcher_0_dma_agent_cp_startofpacket),        //          .startofpacket
		.sink_endofpacket   (output_switcher_0_dma_agent_cp_endofpacket),          //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                    //       src.ready
		.src_valid          (router_src_valid),                                    //          .valid
		.src_data           (router_src_data),                                     //          .data
		.src_channel        (router_src_channel),                                  //          .channel
		.src_startofpacket  (router_src_startofpacket),                            //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                               //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_router router_001 (
		.sink_ready         (spi_system_0_avalon_master_agent_cp_ready),           //      sink.ready
		.sink_valid         (spi_system_0_avalon_master_agent_cp_valid),           //          .valid
		.sink_data          (spi_system_0_avalon_master_agent_cp_data),            //          .data
		.sink_startofpacket (spi_system_0_avalon_master_agent_cp_startofpacket),   //          .startofpacket
		.sink_endofpacket   (spi_system_0_avalon_master_agent_cp_endofpacket),     //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                //       src.ready
		.src_valid          (router_001_src_valid),                                //          .valid
		.src_data           (router_001_src_data),                                 //          .data
		.src_channel        (router_001_src_channel),                              //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                        //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                           //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_router_002 router_002 (
		.sink_ready         (hps_0_f2h_sdram0_data_agent_rp_ready),                               //      sink.ready
		.sink_valid         (hps_0_f2h_sdram0_data_agent_rp_valid),                               //          .valid
		.sink_data          (hps_0_f2h_sdram0_data_agent_rp_data),                                //          .data
		.sink_startofpacket (hps_0_f2h_sdram0_data_agent_rp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (hps_0_f2h_sdram0_data_agent_rp_endofpacket),                         //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                                  //       clk.clk
		.reset              (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                                               //       src.ready
		.src_valid          (router_002_src_valid),                                               //          .valid
		.src_data           (router_002_src_data),                                                //          .data
		.src_channel        (router_002_src_channel),                                             //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                                       //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                                          //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                    //      sink.ready
		.sink_channel       (router_src_channel),                                  //          .channel
		.sink_data          (router_src_data),                                     //          .data
		.sink_startofpacket (router_src_startofpacket),                            //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                              //          .endofpacket
		.sink_valid         (router_src_valid),                                    //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                //          .valid
		.src0_data          (cmd_demux_src0_data),                                 //          .data
		.src0_channel       (cmd_demux_src0_channel),                              //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                        //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                           //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_cmd_demux cmd_demux_001 (
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                //      sink.ready
		.sink_channel       (router_001_src_channel),                              //          .channel
		.sink_data          (router_001_src_data),                                 //          .data
		.sink_startofpacket (router_001_src_startofpacket),                        //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                          //          .endofpacket
		.sink_valid         (router_001_src_valid),                                //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                            //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                            //          .valid
		.src0_data          (cmd_demux_001_src0_data),                             //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                          //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                    //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                       //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (pll_0_outclk0_clk),                                                  //       clk.clk
		.reset               (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                  //       src.ready
		.src_valid           (cmd_mux_src_valid),                                                  //          .valid
		.src_data            (cmd_mux_src_data),                                                   //          .data
		.src_channel         (cmd_mux_src_channel),                                                //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                          //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                            //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                               //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                               //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                             //          .channel
		.sink0_data          (cmd_demux_src0_data),                                                //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                                       //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),                                         //          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                                           //     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                                           //          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),                                         //          .channel
		.sink1_data          (cmd_demux_001_src0_data),                                            //          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),                                   //          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)                                      //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (pll_0_outclk0_clk),                                                  //       clk.clk
		.reset              (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                                               //      sink.ready
		.sink_channel       (router_002_src_channel),                                             //          .channel
		.sink_data          (router_002_src_data),                                                //          .data
		.sink_startofpacket (router_002_src_startofpacket),                                       //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                                         //          .endofpacket
		.sink_valid         (router_002_src_valid),                                               //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                               //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                               //          .valid
		.src0_data          (rsp_demux_src0_data),                                                //          .data
		.src0_channel       (rsp_demux_src0_channel),                                             //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                       //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                                         //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                                               //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                                               //          .valid
		.src1_data          (rsp_demux_src1_data),                                                //          .data
		.src1_channel       (rsp_demux_src1_channel),                                             //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                                       //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                                          //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (pll_0_outclk0_clk),                                   //       clk.clk
		.reset               (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                   //       src.ready
		.src_valid           (rsp_mux_src_valid),                                   //          .valid
		.src_data            (rsp_mux_src_data),                                    //          .data
		.src_channel         (rsp_mux_src_channel),                                 //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                           //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                             //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                              //          .channel
		.sink0_data          (rsp_demux_src0_data),                                 //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                        //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                           //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_rsp_mux rsp_mux_001 (
		.clk                 (pll_0_outclk0_clk),                                   //       clk.clk
		.reset               (Output_Switcher_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                               //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                               //          .valid
		.src_data            (rsp_mux_001_src_data),                                //          .data
		.src_channel         (rsp_mux_001_src_channel),                             //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                       //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                         //          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                                //     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                                //          .valid
		.sink0_channel       (rsp_demux_src1_channel),                              //          .channel
		.sink0_data          (rsp_demux_src1_data),                                 //          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),                        //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)                           //          .endofpacket
	);

	Pyramic_Array_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pll_0_outclk0_clk),                                                  // in_clk_0.clk
		.in_rst_0_reset (hps_0_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //     in_0.data
		.in_0_valid     (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //         .valid
		.in_0_ready     (hps_0_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                       //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                      //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                      //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                       //         .error
	);

endmodule
