	Pyramic_Array u0 (
		.audio_0_external_interface_ADCDAT                (<connected-to-audio_0_external_interface_ADCDAT>),                //                  audio_0_external_interface.ADCDAT
		.audio_0_external_interface_ADCLRCK               (<connected-to-audio_0_external_interface_ADCLRCK>),               //                                            .ADCLRCK
		.audio_0_external_interface_BCLK                  (<connected-to-audio_0_external_interface_BCLK>),                  //                                            .BCLK
		.audio_0_external_interface_DACDAT                (<connected-to-audio_0_external_interface_DACDAT>),                //                                            .DACDAT
		.audio_0_external_interface_DACLRCK               (<connected-to-audio_0_external_interface_DACLRCK>),               //                                            .DACLRCK
		.audio_and_video_config_0_external_interface_SDAT (<connected-to-audio_and_video_config_0_external_interface_SDAT>), // audio_and_video_config_0_external_interface.SDAT
		.audio_and_video_config_0_external_interface_SCLK (<connected-to-audio_and_video_config_0_external_interface_SCLK>), //                                            .SCLK
		.clk_clk                                          (<connected-to-clk_clk>),                                          //                                         clk.clk
		.hps_0_ddr_mem_a                                  (<connected-to-hps_0_ddr_mem_a>),                                  //                                   hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                                 (<connected-to-hps_0_ddr_mem_ba>),                                 //                                            .mem_ba
		.hps_0_ddr_mem_ck                                 (<connected-to-hps_0_ddr_mem_ck>),                                 //                                            .mem_ck
		.hps_0_ddr_mem_ck_n                               (<connected-to-hps_0_ddr_mem_ck_n>),                               //                                            .mem_ck_n
		.hps_0_ddr_mem_cke                                (<connected-to-hps_0_ddr_mem_cke>),                                //                                            .mem_cke
		.hps_0_ddr_mem_cs_n                               (<connected-to-hps_0_ddr_mem_cs_n>),                               //                                            .mem_cs_n
		.hps_0_ddr_mem_ras_n                              (<connected-to-hps_0_ddr_mem_ras_n>),                              //                                            .mem_ras_n
		.hps_0_ddr_mem_cas_n                              (<connected-to-hps_0_ddr_mem_cas_n>),                              //                                            .mem_cas_n
		.hps_0_ddr_mem_we_n                               (<connected-to-hps_0_ddr_mem_we_n>),                               //                                            .mem_we_n
		.hps_0_ddr_mem_reset_n                            (<connected-to-hps_0_ddr_mem_reset_n>),                            //                                            .mem_reset_n
		.hps_0_ddr_mem_dq                                 (<connected-to-hps_0_ddr_mem_dq>),                                 //                                            .mem_dq
		.hps_0_ddr_mem_dqs                                (<connected-to-hps_0_ddr_mem_dqs>),                                //                                            .mem_dqs
		.hps_0_ddr_mem_dqs_n                              (<connected-to-hps_0_ddr_mem_dqs_n>),                              //                                            .mem_dqs_n
		.hps_0_ddr_mem_odt                                (<connected-to-hps_0_ddr_mem_odt>),                                //                                            .mem_odt
		.hps_0_ddr_mem_dm                                 (<connected-to-hps_0_ddr_mem_dm>),                                 //                                            .mem_dm
		.hps_0_ddr_oct_rzqin                              (<connected-to-hps_0_ddr_oct_rzqin>),                              //                                            .oct_rzqin
		.hps_0_io_hps_io_emac1_inst_TX_CLK                (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CLK>),                //                                    hps_0_io.hps_io_emac1_inst_TX_CLK
		.hps_0_io_hps_io_emac1_inst_TXD0                  (<connected-to-hps_0_io_hps_io_emac1_inst_TXD0>),                  //                                            .hps_io_emac1_inst_TXD0
		.hps_0_io_hps_io_emac1_inst_TXD1                  (<connected-to-hps_0_io_hps_io_emac1_inst_TXD1>),                  //                                            .hps_io_emac1_inst_TXD1
		.hps_0_io_hps_io_emac1_inst_TXD2                  (<connected-to-hps_0_io_hps_io_emac1_inst_TXD2>),                  //                                            .hps_io_emac1_inst_TXD2
		.hps_0_io_hps_io_emac1_inst_TXD3                  (<connected-to-hps_0_io_hps_io_emac1_inst_TXD3>),                  //                                            .hps_io_emac1_inst_TXD3
		.hps_0_io_hps_io_emac1_inst_RXD0                  (<connected-to-hps_0_io_hps_io_emac1_inst_RXD0>),                  //                                            .hps_io_emac1_inst_RXD0
		.hps_0_io_hps_io_emac1_inst_MDIO                  (<connected-to-hps_0_io_hps_io_emac1_inst_MDIO>),                  //                                            .hps_io_emac1_inst_MDIO
		.hps_0_io_hps_io_emac1_inst_MDC                   (<connected-to-hps_0_io_hps_io_emac1_inst_MDC>),                   //                                            .hps_io_emac1_inst_MDC
		.hps_0_io_hps_io_emac1_inst_RX_CTL                (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CTL>),                //                                            .hps_io_emac1_inst_RX_CTL
		.hps_0_io_hps_io_emac1_inst_TX_CTL                (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CTL>),                //                                            .hps_io_emac1_inst_TX_CTL
		.hps_0_io_hps_io_emac1_inst_RX_CLK                (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CLK>),                //                                            .hps_io_emac1_inst_RX_CLK
		.hps_0_io_hps_io_emac1_inst_RXD1                  (<connected-to-hps_0_io_hps_io_emac1_inst_RXD1>),                  //                                            .hps_io_emac1_inst_RXD1
		.hps_0_io_hps_io_emac1_inst_RXD2                  (<connected-to-hps_0_io_hps_io_emac1_inst_RXD2>),                  //                                            .hps_io_emac1_inst_RXD2
		.hps_0_io_hps_io_emac1_inst_RXD3                  (<connected-to-hps_0_io_hps_io_emac1_inst_RXD3>),                  //                                            .hps_io_emac1_inst_RXD3
		.hps_0_io_hps_io_sdio_inst_CMD                    (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),                    //                                            .hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0                     (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),                     //                                            .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1                     (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),                     //                                            .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK                    (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),                    //                                            .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2                     (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),                     //                                            .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3                     (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),                     //                                            .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_uart0_inst_RX                    (<connected-to-hps_0_io_hps_io_uart0_inst_RX>),                    //                                            .hps_io_uart0_inst_RX
		.hps_0_io_hps_io_uart0_inst_TX                    (<connected-to-hps_0_io_hps_io_uart0_inst_TX>),                    //                                            .hps_io_uart0_inst_TX
		.hps_0_io_hps_io_gpio_inst_GPIO35                 (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO35>),                 //                                            .hps_io_gpio_inst_GPIO35
		.hps_0_io_hps_io_gpio_inst_GPIO53                 (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO53>),                 //                                            .hps_io_gpio_inst_GPIO53
		.hps_0_io_hps_io_gpio_inst_GPIO54                 (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO54>),                 //                                            .hps_io_gpio_inst_GPIO54
		.pll_0_outclk3_audio_clk                          (<connected-to-pll_0_outclk3_audio_clk>),                          //                         pll_0_outclk3_audio.clk
		.pll_0_sdram_clk                                  (<connected-to-pll_0_sdram_clk>),                                  //                                 pll_0_sdram.clk
		.reset_reset_n                                    (<connected-to-reset_reset_n>),                                    //                                       reset.reset_n
		.spi_system_0_spi_interface_convst0               (<connected-to-spi_system_0_spi_interface_convst0>),               //                  spi_system_0_spi_interface.convst0
		.spi_system_0_spi_interface_convst1               (<connected-to-spi_system_0_spi_interface_convst1>),               //                                            .convst1
		.spi_system_0_spi_interface_convst2               (<connected-to-spi_system_0_spi_interface_convst2>),               //                                            .convst2
		.spi_system_0_spi_interface_cs0_n                 (<connected-to-spi_system_0_spi_interface_cs0_n>),                 //                                            .cs0_n
		.spi_system_0_spi_interface_cs1_n                 (<connected-to-spi_system_0_spi_interface_cs1_n>),                 //                                            .cs1_n
		.spi_system_0_spi_interface_cs2_n                 (<connected-to-spi_system_0_spi_interface_cs2_n>),                 //                                            .cs2_n
		.spi_system_0_spi_interface_miso_00               (<connected-to-spi_system_0_spi_interface_miso_00>),               //                                            .miso_00
		.spi_system_0_spi_interface_miso_01               (<connected-to-spi_system_0_spi_interface_miso_01>),               //                                            .miso_01
		.spi_system_0_spi_interface_miso_10               (<connected-to-spi_system_0_spi_interface_miso_10>),               //                                            .miso_10
		.spi_system_0_spi_interface_miso_11               (<connected-to-spi_system_0_spi_interface_miso_11>),               //                                            .miso_11
		.spi_system_0_spi_interface_miso_20               (<connected-to-spi_system_0_spi_interface_miso_20>),               //                                            .miso_20
		.spi_system_0_spi_interface_miso_21               (<connected-to-spi_system_0_spi_interface_miso_21>),               //                                            .miso_21
		.spi_system_0_spi_interface_reset0                (<connected-to-spi_system_0_spi_interface_reset0>),                //                                            .reset0
		.spi_system_0_spi_interface_reset1                (<connected-to-spi_system_0_spi_interface_reset1>),                //                                            .reset1
		.spi_system_0_spi_interface_reset2                (<connected-to-spi_system_0_spi_interface_reset2>),                //                                            .reset2
		.spi_system_0_spi_interface_sclk0                 (<connected-to-spi_system_0_spi_interface_sclk0>),                 //                                            .sclk0
		.spi_system_0_spi_interface_sclk1                 (<connected-to-spi_system_0_spi_interface_sclk1>),                 //                                            .sclk1
		.spi_system_0_spi_interface_sclk2                 (<connected-to-spi_system_0_spi_interface_sclk2>),                 //                                            .sclk2
		.spi_system_0_spi_interface_busy_or0              (<connected-to-spi_system_0_spi_interface_busy_or0>),              //                                            .busy_or0
		.spi_system_0_spi_interface_busy_or1              (<connected-to-spi_system_0_spi_interface_busy_or1>),              //                                            .busy_or1
		.spi_system_0_spi_interface_busy_or2              (<connected-to-spi_system_0_spi_interface_busy_or2>)               //                                            .busy_or2
	);

